---

- name: Checkout project
  become_user: '{{ dbuser }}'
  git: repo='{{ repo_url }}'
       version=master
       dest='{{ virtualenv }}'
       accept_hostkey=yes
  tags:
      - git
  notify:
      - restart memcached
      - restart gunicorn
      - restart celerybeat
      - restart celeryd
