---

- name: Install PostgreSQL
  apt: pkg={{ item }}
       state=present
       update_cache=yes
  with_items:
    - libpq-dev
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Update postgres client configuration
  template: src={{ item }} dest=/etc/postgresql/9.1/main/{{ item }}
  with_items:
      - pg_hba.conf
      - postgresql.conf

- name: Restart PostgreSQL
  service: name=postgresql state=restarted

- name: Create production database
  become_user: postgres
  postgresql_db: name='{{ dbname }}'
                 encoding='UTF-8'
                 lc_collate='en_GB.utf8'
                 lc_ctype='en_GB.utf8'
                 template='template0'

- name: Add production database user
  become_user: postgres
  postgresql_user: db='{{ dbname }}'
                   name='{{ dbuser }}'
                   password='{{ dbpassword }}'
                   priv='CONNECT/ALL'
                   state=present

- name: Create test database
  become_user: postgres
  postgresql_db: name='test_{{ dbname }}'
                 encoding='UTF-8'
                 lc_collate='en_GB.utf8'
                 lc_ctype='en_GB.utf8'
                 template='template0'
  when: test_db

- name: Add test database user
  become_user: postgres
  postgresql_user: db='test_{{ dbname }}'
                   name='{{ dbuser }}'
                   password='{{ dbpassword }}'
                   priv='CONNECT/ALL'
                   state=present
  when: test_db
