---
- name: Create media directory
  file: path={{ media }} state=directory owner={{ dbuser }} mode=0775

- name: Create static directory
  file: path={{ static }} state=directory owner={{ dbuser }} mode=0775

- name: Collect static files
  become_user: '{{ dbuser }}'
  command: '{{ virtualenv }}exec {{ item }}'
  with_items:
    - collectstatic --noinput --verbosity=0
