---

- name: Upload celerybeat startup script
  copy: src='celerybeat' dest='/etc/init.d/celerybeat' mode=0744
  notify: restart celerybeat

- name: Upload celeryd startup script
  copy: src='celeryd' dest='/etc/init.d/celeryd' mode=0744

- name: Upload celeryd configuration
  template: src='celeryd' dest='/etc/default/celeryd' mode=0644
  notify: restart celeryd
