---

- name: Install Redis
  apt: pkg=redis-server state=present

- name: Open Redis to web servers
  template: src=redis.conf dest=/etc/redis/redis.conf
  notify: restart redis

- name: Create a Celery user
  user: name=celery state=present system=yes

- name: Upload celerybeat startup script
  copy: src='celerybeat' dest='/etc/init.d/celerybeat' mode=0744
  notify: restart celerybeat

- name: Upload celeryd startup script
  copy: src='celeryd' dest='/etc/init.d/celeryd' mode=0744

- name: Upload celeryd configuration
  template: src='celeryd' dest='/etc/default/celeryd' mode=0644
  notify: restart celeryd
