---

- hosts: db
  become: yes
  roles:
      - database
  vars:
      test_db: yes
  vars_files:
      - vars/apis/development.yaml

- hosts: web
  become: yes
  roles:
      - app
      - runserver
  vars:
      test_web: yes
  vars_files:
      - vars/apis/development.yaml

- hosts: workers
  become: yes
  roles:
      - app
      - celery
  vars_files:
      - vars/apis/development.yaml
