---
- name: Install nginx web server
  apt: pkg=nginx state=installed

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/sites-enabled/default
  notify: restart nginx
  tags:
  - web
  - nginx
