---
- name: Install gunicorn
  pip: name=gunicorn
       virtualenv='{{ virtualenv }}'

- name: Copy gunicorn configuration
  template: src=gunicorn.conf dest=/etc/init/gunicorn.conf mode=0644
  tags:
      - web
